project_id = "kcihftfgmsrpcljsbjdj"

[functions]
  [functions.alibaba-1688-cached-search]
    verify_jwt = false
  [functions.alibaba-1688-image-search]
    verify_jwt = false
  [functions.alibaba-1688-item-get]
    verify_jwt = false
  [functions.alibaba-1688-search]
    verify_jwt = false
  [functions.alibaba-1688-shipping-fee]
    verify_jwt = false
  [functions.alibaba-1688-seller-products]
    verify_jwt = false
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.firecrawl-map]
    verify_jwt = false
  [functions.firecrawl-scrape]
    verify_jwt = false
  [functions.firecrawl-search]
    verify_jwt = false
  [functions.paystation-init-payment]
    verify_jwt = false
  [functions.paystation-verify-payment]
    verify_jwt = false
  [functions.send-sms-otp]
    verify_jwt = false
  [functions.verify-sms-otp]
    verify_jwt = false
